### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by Lolcroc** [SoftwareQuTech/SimulaQron#127]
I'm running `sh tests/runTests.sh --quick` inside Git Bash, but get the following error:

`Yves@Yves-PC MINGW64 ~/Development/Python/SimulaQron (master)
$ sh tests/runTests.sh --quick
Starting tests (using projectq as backend)
Starting logging server
Started logging server
Testing cqc headers..
: Cannot start classical communication servers.

Traceback (most recent call last):
  File "C:\Users\Yves\Development\Python\SimulaQron\cqc\pythonLib\cqc.py", line 265, in __init__
    self._s.connect(addr[4])
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Yves/Development/Python/SimulaQron/tests/auto/cqc/testCQCMessages.py", line 967, in <module>
    unittest.main()
  File "C:\Users\Yves\Anaconda3\Lib\unittest\main.py", line 101, in __init__
    self.runTests()
  File "C:\Users\Yves\Anaconda3\Lib\unittest\main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "C:\Users\Yves\Anaconda3\Lib\unittest\runner.py", line 176, in run
    test(result)
  File "C:\Users\Yves\Anaconda3\Lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Yves\Anaconda3\Lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Yves\Anaconda3\Lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Yves\Anaconda3\Lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\Yves\Anaconda3\Lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\Yves\Anaconda3\Lib\unittest\case.py", line 615, in run
    testMethod()
  File "C:/Users/Yves/Development/Python/SimulaQron/tests/auto/cqc/testCQCMessages.py", line 900, in testAllocate0
    with CQCConnection("Alice", appID=1) as alice:
  File "C:\Users\Yves\Development\Python\SimulaQron\cqc\pythonLib\cqc.py", line 265, in __init__
    self._s.connect(addr[4])
KeyboardInterrupt
`

I have no idea how to continue

**Comment by AckslD** [comment]
Hello @Lolcroc 

Unfortunately I am not sure if SimulaQron will work on Windows 7 or lower. I would recommend you to upgrade to Windows 10 and install the bash terminal or install Linux next to your current operating system.

**Comment by AckslD** [comment]
@Lolcroc 
Could you try again but using the branch `fix_for_windows` instead.
