### ISSUE TITLE
Basic Example Fails with method not found error 

### ISSUE THREAD

**Issue by syed2019** [SoftwareQuTech/SimulaQron#212]
Following error while running Example 

twisted.spread.flavors.NoSuchMethod: No such method: remote_add_register

Critical error:  [Failure instance: Traceback from remote host -- twisted.spread.flavors.NoSuchMethod: No such method: remote_add_register
]
2019-08-26 21:13:04,159:DEBUG:LOCAL Bob: All connections set up.
2019-08-26 21:13:04,159:DEBUG:LOCAL Bob: Connected node Alice with <twisted.spread.pb.RemoteReference object at 0x7f88339d55c0>
Peer will receive following PB traceback:
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/twisted/spread/banana.py", line 173, in gotItem
    self.callExpressionReceived(item)
  File "/usr/local/lib/python3.6/dist-packages/twisted/spread/banana.py", line 136, in callExpressionReceived
    self.expressionReceived(obj)
  File "/usr/local/lib/python3.6/dist-packages/twisted/spread/pb.py", line 621, in expressionReceived
    method(*sexp[1:])
  File "/usr/local/lib/python3.6/dist-packages/twisted/spread/pb.py", line 1025, in proto_message
    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/dist-packages/twisted/spread/pb.py", line 1054, in _recvMessage
    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/spread/flavors.py", line 123, in remoteMessageReceived
    raise NoSuchMethod("No such method: remote_%s" % (message,))
twisted.spread.flavors.NoSuchMethod: No such method: remote_add_register

Critical error:  [Failure instance: Traceback from remote host -- twisted.spread.flavors.NoSuchMethod: No such method: remote_add_register

Followed instruction from https://softwarequtech.github.io/SimulaQron/html/

Can anyone help me to understand whats going on.

**Comment by AckslD** [comment]
Closing this due to no response
