### ISSUE TITLE
Starting network from in python example doesn't work

### ISSUE THREAD

**Issue by Shyadow** [SoftwareQuTech/SimulaQron#220]
When I try running the example here: https://softwarequtech.github.io/SimulaQron/html/ConfNodes.html#starting-a-network-from-python I get an error.

When I do 'python test.py' in the terminal, it prints:
`Do you want to add/replace the network test in the file /home/liam/MEP/simulaqron_exercises/testexample/tempvenv/lib/python3.7/site-packages/simulaqron/config/network.jsonwith a network constisting of the nodes ['Alice', 'Bob', 'Charlie']?`

When I type yes, it prints the same message 6 times in a row. 

If I type yes after that, it gives the following:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liam/MEP/simulaqron_exercises/testexample/test.py", line 9, in <module>
    network.start()
  File "/home/liam/MEP/simulaqron_exercises/testexample/tempvenv/lib/python3.7/site-packages/simulaqron/network.py", line 169, in start
    p.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by AckslD** [comment]
Hi @Shyadow!

Ah right, I forgot the the code needs to be guarded by the `__name__ == '__main__'` gatekeeper check. The code should be:

```python
from simulaqron.network import Network


def main():
    # Setup the network
    nodes = ["Alice", "Bob", "Charlie"]
    topology = {"Alice": ["Bob"], "Bob": ["Alice", "Charlie"], "Charlie": ["Bob"]}
    network = Network(name="test", nodes=nodes, topology=topology)

    # Start the network
    network.start()

    input("To stop the network, press enter...")


if __name__ == '__main__':
    main()
```

Note that I also added a call to `input` since otherwise the network will be closed whenever `network` goes out of scope.

I will update the example in the docs. Let me know if this works for you in the meantime.

**Comment by AckslD** [comment]
@Shyadow try to set the argument `network_name` in the `CQCConnection` as:
```python
    with CQCConnection("Alice", network_name="test") as Alice:
```

**Comment by Shyadow** [comment]
That seems to work.
