### ISSUE TITLE
Problem with the enumeration in the SimulaQron package

### ISSUE THREAD

**Issue by fjlc-73** [SoftwareQuTech/SimulaQron#282]
Traceback (most recent call last):
  File "/Users/javi/venv/bin/simulaqron", line 5, in <module>
    from simulaqron.simulaqron import cli
  File "/Users/javi/venv/lib/python3.8/site-packages/simulaqron/simulaqron.py", line 234, in <module>
    @click.argument('value', type=click.Choice([b.value for b in SimBackend.value]))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 346, in __getattr__
    raise AttributeError(name) from None
AttributeError: value

**Comment by AckslD** [comment]
What version/branch are you using? This is not what the line is currently in master:
https://github.com/SoftwareQuTech/SimulaQron/blob/master/simulaqron/simulaqron.py#L234
